=== JigSawFr/PlayInsights/schemas/platforms/3do/similar.schema.json
{
 "$schema": "https://json-schema.org/draft/2020-12/schema",
 "title": "Each game's most alike: [[id, 1..100]]",
 "type": "object",
 "required": [
  "schema",
  "generated",
  "games"
 ],
 "properties": {
  "schema": {
   "const": 1
  },
  "generated": {
   "type": "string",
   "pattern": "^\\d{4}-\\d{2}-\\d{2}$"
  },
  "source": {
   "type": "string"
  },
  "platform": {
   "type": "string"
  },
  "license": {
   "type": "string"
  },
  "part": {
   "type": "integer"
  },
  "parts": {
   "type": "integer"
  },
  "games": {
   "type": "object",
   "additionalProperties": {
    "type": "array",
    "items": {
     "type": "array",
     "minItems": 2,
     "maxItems": 2,
     "prefixItems": [
      {
       "type": "string"
      },
      {
       "type": "integer",
       "minimum": 1,
       "maximum": 100
      }
     ]
    }
   }
  }
 },
 "$id": "https://cdn.jsdelivr.net/gh/JigSawFr/Atlas@data/schemas/platforms/3do/similar.schema.json"
}

=== JigSawFr/PlayInsights/platforms/atari2600/similar.json
{"schema":1,"platform":"atari2600","generated":"2026-10-30","source":"platforms/atari2600/games.json's traits","games":{"Q12384":[["Q2264301",90],["Q2303119",32],["Q610968",12],["Q91247",12],["Q138786980",7],["Q5506197",7],["Q6925026",5],["Q1422227",3],["Q2214754",3],["Q4810728",3],["Q7353649",2],["Q6129971",2]],"Q29715":[["Q4812844",84],["Q4133050",81],["Q7690375",80],["Q7112009",78],["Q4923044",75],["Q7927865",75],["Q4810728",73],["Q4951133",72],["Q5299751",72],["Q5580552",72],["Q7605932",72],["Q7541410",70]],"Q54317":[["Q105621215",18],["Q105637148",18],["Q1192794",18],["Q2646223",18],["Q2588960",17],["Q2589426",17],["Q105626635",17],["Q105639732",17],["Q105763900",17],["Q141429379",16],["Q7537302",15],["Q7646895",15]],"Q54325":[["Q54331",95],["Q6680121",93],["Q6129971",91],["Q7601092",89],["Q5505259",33],["Q133883927",24],["Q22908982",24],["Q4698161",24],["Q4808556",24],["Q5782590",24],["Q7601891",24],["Q771794",15]],"Q54331":[["Q54325",95],["Q6680121",88],["Q6129971",86],["Q7601092",85],["Q5505259",31],["Q133883927",22],["Q22908982",22],["Q4698161",22],["Q4808556",22],["Q5782590",22],["Q7601891",22],["Q771794",14]],"Q55616":[["Q105626635",19],["Q105639732",19],["Q105763900",19],["Q141429379",18],["Q105621215",17],["Q105637148",17],["Q1192794",17],["Q2646223",17],["Q7537302",17],["Q7646895",17],["Q122826958",17],["Q2626874",16]],"Q88604":[["Q4812844",72],["Q7690375",68],["Q4810728",67],["Q7112009",67],["Q4133050",65],["Q7541410",65],["Q4951133",61],["Q5299751",61],["Q5580552",61],["Q7605932",61],["Q29715",60],["Q4923044",60]],"Q88855":[["Q454924",93],["Q1790249",36],["Q2841397",30],["Q8273133",25],["Q4951133",16],["Q5299751",16],["Q5455016",16],["Q5580552",16],["Q7605932",16],["Q4923044",15],["Q7927865",15],["Q7535140",15]],"Q88972":[["Q2527852",100],["Q475055",100],["Q7602119",100],["Q7241701",93],["Q20874771",89],["Q4034859",89],["Q644479",89],["Q259486",86],["Q2788606",86],["Q7597473",86],["Q1422227",84],["Q2214754",84]],"Q91247":[["Q2939793",30],["Q2762472",27],["Q5250293",27],["Q3496992",25],["Q1125773",23],["Q7673660",20],["Q4944681",16],["Q12384",12],["Q133883927",8],["Q22908982",8],["Q4698161",8],["Q4808556",8]],"Q130678":[["Q4812844",72],["Q7690375",69],["Q4810728",68],["Q7112009",67],["Q4133050",66],["Q7541410",65],["Q4951133",62],["Q5299751",62],["Q5580552",62],["Q7605932",62],["Q29715",61],["Q4923044",61]],"Q164478":[["Q2669734",88],["Q2936913",59],["Q2869418",39],["Q1192318",35],["Q16144871",29]],"Q173626":[["Q204105",93],["Q1337036",89],["Q1192514",35],["Q20874777",20],["Q7853294",19],["Q2104469",19],["Q5087226",19],["Q2626874",13],["Q6007844",13],["Q1142341",12],["Q4726393",12],["Q1572086",12]],"Q177491":[["Q85760981",21],["Q7537302",19],["Q7646895",19],["Q105626635",19],["Q105639732",19],["Q105763900",19],["Q1507926",18],["Q141429379",18],["Q1142341",18],["Q105621215",17],["Q105637148",17],["Q1192794",17]],"Q182251":[["Q141429379",76],["Q1507926",76],["Q2588960",73],["Q2589426",73],["Q105626635",73],["Q105639732",73],["Q105763900",73],["Q7537302",71],["Q7646895",71],["Q105621215",67],["Q105637148",67],["Q1192794",67]],"Q204105":[["Q173626",93],["Q1337036",93],["Q1192514",36],["Q138771986",18],["Q138795405",18],["Q17151091",18],["Q2069424",18],["Q21190222",18],["Q2675300",18],["Q2682583",18],["Q2741259",18],["Q2741292",18]],"Q220665":[["Q1040033",98],["Q5183115",87],["Q7209123",83],["Q1713469",75],["Q4914584",67],["Q591171",30],["Q124618554",28],["Q133883927",24],["Q22908982",24],["Q4698161",24],["Q4808556",24],["Q5782590",24]],"Q259486":[["Q2788606",100],["Q7597473",100],["Q20874771",97],["Q4034859",97],["Q644479",97],["Q7241701",92],["Q2527852",86],["Q475055",86],["Q7602119",86],["Q88972",86],["Q1422227",83],["Q2214754",83]],"Q344361":[["Q7241701",72],["Q20874771",69],["Q4034859",69],["Q644479",69],["Q2527852",67],["Q475055",67],["Q7602119",67],["Q88972",67],["Q259486",67],["Q2788606",67],["Q7597473",67],["Q1422227",65]],"Q379915":[["Q2100878",100],["Q977919",100],["Q16167812",98],["Q105626635",83],["Q105639732",83],["Q105763900",83],["Q141429379",80],["Q105621215",75],["Q105637148",75],["Q1192794",75],["Q2646223",75],["Q7537302",75]],"Q445221":[["Q133883927",17],["Q22908982",17],["Q4698161",17],["Q4808556",17],["Q5782590",17],["Q7601891",17],["Q771794",11],["Q517640",10],["Q105621215",7],["Q105637148",7],["Q1192794",7],["Q2646223",7]],"Q454924":[["Q88855",93],["Q1790249",34],["Q2841397",30],["Q8273133",25],["Q4951133",15],["Q5299751",15],["Q5455016",15],["Q5580552",15],["Q7605932",15],["Q4923044",15],["Q7927865",15],["Q7535140",15]],"Q474102":[["Q123018666",94],["Q5287827",56],["Q7622905",56],["Q10302032",54],["Q10290923",50],["Q5305511",50],["Q16267626",49],["Q2835899",49],["Q19706867",48],["Q2762472",36],["Q1337036",32],["Q2623012",30]],"Q475051":[["Q7241701",72],["Q20874771",69],["Q4034859",69],["Q644479",69],["Q2527852",67],["Q475055",67],["Q7602119",67],["Q88972",67],["Q259486",67],["Q2788606",67],["Q7597473",67],["Q1422227",65]],"Q475055":[["Q2527852",100],["Q7602119",100],["Q88972",100],["Q7241701",93],["Q20874771",89],["Q4034859",89],["Q644479",89],["Q259486",86],["Q2788606",86],["Q7597473",86],["Q1422227",84],["Q2214754",84]],"Q488692":[["Q1517301",85],["Q20874777",18],["Q7853294",17],["Q2104469",17],["Q5087226",17],["Q1142341",16],["Q138771986",15],["Q138795405",15],["Q17151091",15],["Q2069424",15],["Q21190222",15],["Q2675300",15]],"Q499021":[["Q138786980",21],["Q5506197",18],["Q6925026",15],["Q1422227",9],["Q2214754",9],["Q4810728",9],["Q7353649",7],["Q6129971",6],["Q106489720",6],["Q6680121",6],["Q138678542",6],["Q888718",6]],"Q517640":[["Q133883927",58],["Q22908982",58],["Q4698161",58],["Q4808556",58],["Q5782590",58],["Q7601891",58],["Q771794",36],["Q105621215",24],["Q105637148",24],["Q1192794",24],["Q2646223",24],["Q2588960",23]],"Q524267":[["Q5505259",79],["Q1199765",35],["Q1151504",33],["Q2753199",33],["Q1815131",32],["Q7353649",31],["Q3776897",29],["Q7856907",27],["Q917503",27],["Q1630875",10],["Q138771986",8],["Q138795405",8]],"Q591171":[["Q1713469",39],["Q1040033",30],["Q220665",30],["Q5183115",29],["Q7209123",28],["Q4914584",21],["Q138786980",10],["Q124618554",9],["Q5506197",9],["Q6925026",7],["Q138771986",7],["Q138795405",7]],"Q597257":[["Q29715",25],["Q4812844",22],["Q7690375",20],["Q7112009",20],["Q4133050",20],["Q4810728",19],["Q4951133",18],["Q5299751",18],["Q5580552",18],["Q7605932",18],["Q4923044",18],["Q7927865",18]],"Q610968":[["Q2264301",13],["Q12384",12],["Q138786980",10],["Q5506197",9],["Q6925026",7],["Q1422227",4],["Q2214754",4],["Q4810728",4],["Q2303119",4],["Q7353649",3],["Q6129971",3],["Q106489720",3]],"Q611289":[["Q138786980",15],["Q5506197",13],["Q6925026",11],["Q1422227",6],["Q2214754",6],["Q4810728",6],["Q7353649",5],["Q6129971",4],["Q106489720",4],["Q6680121",4],["Q138678542",4],["Q888718",4]],"Q644479":[["Q20874771",100],["Q4034859",100],["Q259486",97],["Q2788606",97],["Q7597473",97],["Q7241701",96],["Q2527852",89],["Q475055",89],["Q7602119",89],["Q88972",89],["Q1422227",86],["Q2214754",86]],"Q677764":[["Q4033261",29],["Q4955766",29],["Q5805565",29],["Q138773485",25],["Q100701966",12],["Q7555897",11],["Q1565343",11],["Q1014915",9],["Q917027",8]],"Q698705":[["Q1319139",8]],"Q748890":[["Q4188002",98],["Q7572546",27],["Q124540344",26],["Q105626635",21],["Q105639732",21],["Q105763900",21],["Q1136685",20],["Q141429379",20],["Q105621215",19],["Q105637148",19],["Q1192794",19],["Q2646223",19]],"Q771794":[["Q133883927",62],["Q22908982",62],["Q4698161",62],["Q4808556",62],["Q5782590",62],["Q7601891",62],["Q517640",36],["Q105621215",26],["Q105637148",26],["Q1192794",26],["Q2646223",26],["Q2588960",25]],"Q829331":[["Q133883927",17],["Q22908982",17],["Q4698161",17],["Q4808556",17],["Q5782590",17],["Q7601891",17],["Q20874777",16],["Q7853294",15],["Q2104469",15],["Q5087226",15],["Q3776897",13],["Q771794",10]],"Q888718":[["Q138678542",100],["Q28677562",94],["Q138676015",90],["Q138672824",86],["Q138786980",28],["Q5506197",25],["Q6925026",21],["Q1422227",12],["Q2214754",12],["Q4810728",12],["Q7353649",9],["Q6129971",8]],"Q917027":[["Q4033261",29],["Q4955766",29],["Q5805565",29],["Q138773485",25],["Q20874777",16],["Q7853294",15],["Q2104469",14],["Q5087226",14],["Q100701966",12],["Q7555897",11],["Q1565343",11],["Q2626874",10]],"Q917503":[["Q1199765",77],["Q1151504",76],["Q2753199",76],["Q1815131",73],["Q7353649",72],["Q3776897",68],["Q7856907",64],["Q524267",27],["Q1630875",24]],"Q950338":[["Q138771986",14],["Q138795405",14],["Q17151091",14],["Q2069424",14],["Q21190222",14],["Q2675300",14],["Q2682583",14],["Q2741259",14],["Q2741292",14],["Q2741447",14],["Q4038649",14],["Q50100143",14]],"Q968020":[["Q1053648",97],["Q105621215",24],["Q105637148",24],["Q1192794",24],["Q2646223",24],["Q2588960",22],["Q2589426",22],["Q105626635",21],["Q105639732",21],["Q105763900",21],["Q141429379",21],["Q7537302",19]],"Q977919":[["Q2100878",100],["Q379915",100],["Q16167812",98],["Q105626635",83],["Q105639732",83],["Q105763900",83],["Q141429379",80],["Q105621215",75],["Q105637148",75],["Q1192794",75],["Q2646223",75],["Q7537302",75]],"Q1014915":[["Q2623012",84],["Q1093914",83],["Q4033261",32],["Q4955766",32],["Q5805565",32],["Q138773485",28],["Q138786980",23],["Q5506197",20],["Q1565343",19],["Q6925026",17],["Q100701966",14],["Q7555897",13]],"Q1040033":[["Q220665",98],["Q5183115",89],["Q7209123",85],["Q1713469",77],["Q4914584",69],["Q591171",30],["Q124618554",29],["Q133883927",25],["Q22908982",25],["Q4698161",25],["Q4808556",25],["Q5782590",25]],"Q1053648":[["Q968020",97],["Q182251",27],["Q105626635",21],["Q105639732",21],["Q105763900",21],["Q141429379",20],["Q1507926",20],["Q2588960",20],["Q2589426",20],["Q105621215",19],["Q105637148",19],["Q1192794",19]],"Q1093914":[["Q2623012",89],["Q1014915",83],["Q20874777",20],["Q7853294",19],["Q2104469",18],["Q5087226",18],["Q2626874",13],["Q6007844",13],["Q1142341",12],["Q4726393",12],["Q8028724",11],["Q7541410",11]],"Q1115150":[["Q133883927",8],["Q22908982",8],["Q4698161",8],["Q4808556",8],["Q5782590",8],["Q7601891",8],["Q771794",5],["Q517640",4],
