=== JigSawFr/PlayInsights/schemas/platforms/amstradcpc/popular.schema.json
{
 "$schema": "https://json-schema.org/draft/2020-12/schema",
 "title": "A platform's games' renown: [score 0..100, trend -100..999, critics 0..100]",
 "type": "object",
 "required": [
  "schema",
  "generated",
  "games"
 ],
 "properties": {
  "schema": {
   "const": 1
  },
  "generated": {
   "type": "string",
   "pattern": "^\\d{4}-\\d{2}-\\d{2}$"
  },
  "source": {
   "type": "string"
  },
  "platform": {
   "type": "string"
  },
  "license": {
   "type": "string"
  },
  "part": {
   "type": "integer"
  },
  "parts": {
   "type": "integer"
  },
  "month": {
   "type": "string"
  },
  "views": {
   "type": "boolean"
  },
  "trends": {
   "type": "string",
   "pattern": "^\\d{4}-\\d{2}-\\d{2}$"
  },
  "games": {
   "type": "object",
   "additionalProperties": {
    "type": "array",
    "minItems": 3,
    "maxItems": 3,
    "prefixItems": [
     {
      "type": "integer",
      "minimum": 0,
      "maximum": 100
     },
     {
      "type": "integer",
      "minimum": -100,
      "maximum": 999
     },
     {
      "type": "integer",
      "minimum": 0,
      "maximum": 100
     }
    ]
   }
  }
 },
 "$id": "https://cdn.jsdelivr.net/gh/JigSawFr/Atlas@data/schemas/platforms/amstradcpc/popular.schema.json"
}

=== JigSawFr/PlayInsights/platforms/gbc/popular.json
{"schema":1,"platform":"gbc","generated":"2026-10-30","month":"2026-09","views":true,"source":"Wikidata (P400, sitelinks), Wikimedia pageviews (en.wikipedia)","games":{"Q52053":[10,0,0],"Q54842":[14,0,0],"Q55217":[21,0,0],"Q88240":[17,0,0],"Q88759":[57,-8,0],"Q91220":[21,0,0],"Q94460":[69,4,0],"Q173626":[73,18,0],"Q220665":[67,11,0],"Q254723":[18,0,0],"Q278771":[22,0,0],"Q288296":[21,0,0],"Q288346":[10,0,0],"Q445295":[15,0,0],"Q518987":[62,1,0],"Q524267":[61,5,0],"Q596596":[22,0,0],"Q598160":[10,0,0],"Q625278":[14,0,0],"Q645418":[21,0,0],"Q660034":[18,0,0],"Q677764":[18,0,0],"Q723623":[14,0,0],"Q726167":[59,16,0],"Q738725":[18,0,0],"Q776134":[17,0,0],"Q785735":[17,0,0],"Q820527":[17,0,0],"Q914334":[16,0,0],"Q919857":[22,0,0],"Q925269":[23,0,0],"Q933822":[10,0,0],"Q938360":[8,0,0],"Q945899":[18,0,0],"Q953922":[21,0,0],"Q956303":[21,0,0],"Q969612":[18,0,0],"Q972268":[20,0,0],"Q1053648":[22,0,0],"Q1060323":[64,61,0],"Q1064350":[22,0,0],"Q1126115":[17,0,0],"Q1143139":[17,0,0],"Q1149174":[14,0,0],"Q1171293":[19,0,0],"Q1192514":[23,0,0],"Q1192794":[21,0,0],"Q1241664":[22,0,0],"Q1328570":[17,0,0],"Q1330205":[21,0,0],"Q1451169":[14,0,0],"Q1463730":[21,0,0],"Q1464617":[18,0,0],"Q1565343":[22,0,0],"Q1571488":[17,0,0],"Q1632811":[16,0,0],"Q1635462":[21,0,0],"Q1788165":[17,0,0],"Q1856575":[5,0,0],"Q1860996":[16,0,0],"Q1988120":[58,-7,0],"Q1998483":[14,0,0],"Q2015773":[15,0,0],"Q2019427":[12,0,0],"Q2029195":[22,0,0],"Q2039766":[14,0,0],"Q2045111":[16,0,0],"Q2078596":[17,0,0],"Q2081133":[21,0,0],"Q2135136":[21,0,0],"Q2141683":[23,0,0],"Q2201706":[16,0,0],"Q2264782":[21,0,0],"Q2273753":[21,0,0],"Q2310820":[18,0,0],"Q2313869":[22,0,0],"Q2337936":[21,0,0],"Q2351151":[16,0,0],"Q2351827":[61,-6,0],"Q2356104":[17,0,0],"Q2366720":[19,0,0],"Q2386012":[20,0,0],"Q2443162":[17,0,0],"Q2447854":[19,0,0],"Q2451909":[19,0,0],"Q2494597":[14,0,0],"Q2560049":[19,0,0],"Q2562585":[20,0,0],"Q2562672":[21,0,0],"Q2591858":[17,0,0],"Q2600361":[18,0,0],"Q2706771":[17,0,0],"Q2710825":[14,0,0],"Q2717834":[19,0,0],"Q2722404":[12,0,0],"Q2742912":[15,0,0],"Q2745604":[12,0,0],"Q2758074":[17,0,0],"Q2758082":[18,0,0],"Q2836700":[14,0,0],"Q2862833":[14,0,0],"Q2862835":[16,0,0],"Q2875256":[14,0,0],"Q2891437":[14,0,0],"Q2891582":[16,0,0],"Q2891778":[14,0,0],"Q2905942":[5,0,0],"Q2909725":[15,0,0],"Q2928773":[12,0,0],"Q2947434":[14,0,0],"Q2963395":[17,0,0],"Q2985774":[12,0,0],"Q3005559":[15,0,0],"Q3038722":[12,0,0],"Q3038754":[15,0,0],"Q3041086":[5,0,0],"Q3084347":[17,0,0],"Q3133955":[12,0,0],"Q3235095":[10,0,0],"Q3276305":[16,0,0],"Q3276912":[11,0,0],"Q3283766":[11,0,0],"Q3284542":[11,0,0],"Q3311829":[11,0,0],"Q3334615":[11,0,0],"Q3375307":[14,0,0],"Q3411120":[15,0,0],"Q3421556":[11,0,0],"Q3493444":[16,0,0],"Q3515891":[20,0,0],"Q3516382":[10,0,0],"Q3529535":[5,0,0],"Q3551619":[11,0,0],"Q3611777":[10,0,0],"Q3646676":[12,0,0],"Q3782923":[10,0,0],"Q3853929":[5,0,0],"Q3882542":[5,0,0],"Q3886110":[11,0,0],"Q3930487":[8,0,0],"Q3933909":[10,0,0],"Q3978766":[12,0,0],"Q3987774":[5,0,0],"Q4021193":[12,0,0],"Q4021199":[15,0,0],"Q4035127":[14,0,0],"Q4035488":[10,0,0],"Q4037876":[11,0,0],"Q4039658":[12,0,0],"Q4049863":[12,0,0],"Q4546897":[5,0,0],"Q4677120":[10,0,0],"Q4742157":[16,0,0],"Q4765202":[8,0,0],"Q4777508":[14,0,0],"Q4777509":[10,0,0],"Q4785071":[10,0,0],"Q4797710":[5,0,0],"Q4823238":[11,0,0],"Q5003536":[16,0,0],"Q5231242":[12,0,0],"Q5268360":[14,0,0],"Q5283792":[10,0,0],"Q5288724":[8,0,0],"Q5300226":[8,0,0],"Q5359710":[10,0,0],"Q5399203":[10,0,0],"Q5422374":[5,0,0],"Q5445318":[5,0,0],"Q5483464":[5,0,0],"Q5520530":[10,0,0],"Q5520534":[10,0,0],"Q5520537":[11,0,0],"Q5708750":[11,0,0],"Q5743244":[11,0,0],"Q5922850":[8,0,0],"Q6341335":[14,0,0],"Q6349722":[8,0,0],"Q6406209":[5,0,0],"Q6415166":[12,0,0],"Q6434143":[10,0,0],"Q6492533":[8,0,0],"Q6498545":[14,0,0],"Q6547375":[8,0,0],"Q6651158":[11,0,0],"Q6675663":[11,0,0],"Q6675674":[14,0,0],"Q6699624":[14,0,0],"Q6822711":[5,0,0],"Q6878465":[12,0,0],"Q6900797":[8,0,0],"Q6902808":[8,0,0],"Q6902811":[10,0,0],"Q6902876":[14,0,0],"Q6952673":[10,0,0],"Q7071857":[8,0,0],"Q7228925":[12,0,0],"Q7236403":[11,0,0],"Q7249303":[5,0,0],"Q7271465":[5,0,0],"Q7271470":[12,0,0],"Q7353296":[14,0,0],"Q7378616":[8,0,0],"Q7470389":[14,0,0],"Q7489029":[18,0,0],"Q7548028":[10,0,0],"Q7572413":[8,0,0],"Q7578979":[17,0,0],"Q7600814":[14,0,0],"Q7642251":[5,0,0],"Q7687444":[10,0,0],"Q7750522":[8,0,0],"Q7808639":[8,0,0],"Q7857517":[5,0,0],"Q7861437":[8,0,0],"Q7885948":[12,0,0],"Q7897206":[5,0,0],"Q7958822":[11,0,0],"Q7963953":[17,0,0],"Q7969514":[10,0,0],"Q8035638":[8,0,0],"Q9359604":[11,0,0],"Q10268706":[8,0,0],"Q10268707":[5,0,0],"Q10290340":[5,0,0],"Q11196410":[5,0,0],"Q11270700":[8,0,0],"Q11271773":[10,0,0],"Q11299749":[5,0,0],"Q11317491":[5,0,0],"Q11322148":[14,0,0],"Q11322840":[8,0,0],"Q11329532":[8,0,0],"Q11335038":[5,0,0],"Q11343666":[5,0,0],"Q11344661":[5,0,0],"Q11361734":[11,0,0],"Q11431230":[11,0,0],"Q13219473":[23,0,0],"Q14545597":[12,0,0],"Q14906476":[11,0,0],"Q14956241":[8,0,0],"Q15618570":[8,0,0],"Q16041177":[8,0,0],"Q16259740":[10,0,0],"Q16262935":[11,0,0],"Q16267583":[8,0,0],"Q16267589":[14,0,0],"Q16267716":[8,0,0],"Q16267750":[10,0,0],"Q16555066":[10,0,0],"Q16655229":[8,0,0],"Q16677736":[12,0,0],"Q17042730":[15,0,0],"Q17494453":[20,0,0],"Q17985733":[10,0,0],"Q18087995":[10,0,0],"Q18149321":[11,0,0],"Q18279981":[8,0,0],"Q18754123":[5,0,0],"Q19707296":[11,0,0],"Q20380235":[5,0,0],"Q21039925":[10,0,0],"Q21563313":[5,0,0],"Q22019737":[8,0,0],"Q25397610":[5,0,0],"Q25991443":[10,0,0],"Q25991446":[10,0,0],"Q28126588":[11,0,0],"Q28127215":[12,0,0],"Q28127368":[8,0,0],"Q28417154":[8,0,0],"Q28452472":[5,0,0],"Q28452572":[5,0,0],"Q28452644":[5,0,0],"Q28496887":[5,0,0],"Q29838430":[5,0,0],"Q29854446":[5,0,0],"Q29867432":[8,0,0],"Q29888287":[8,0,0],"Q29964552":[5,0,0],"Q30591082":[11,0,0],"Q30591282":[5,0,0],"Q30925427":[5,0,0],"Q33890877":[10,0,0],"Q39058559":[8,0,0],"Q39070413":[10,0,0],"Q39073874":[8,0,0],"Q39306034":[8,0,0],"Q41385173":[5,0,0],"Q41385911":[5,0,0],"Q41386124":[5,0,0],"Q47473836":[5,0,0],"Q48703014":[10,0,0],"Q50991221":[5,0,0],"Q51000295":[8,0,0],"Q51077559":[5,0,0],"Q51556086":[8,0,0],"Q55622305":[5,0,0],"Q58864649":[10,0,0],"Q63225525":[8,0,0],"Q63228536":[5,0,0],"Q64711789":[5,0,0],"Q67113842":[8,0,0],"Q67124883":[5,0,0],"Q67145841":[10,0,0],"Q67179858":[5,0,0],"Q67388656":[8,0,0],"Q67388756":[8,0,0],"Q67433277":[8,0,0],"Q67766220":[8,0,0],"Q72615128":[5,0,0],"Q74014645":[5,0,0],"Q86735271":[5,0,0],"Q92776707":[5,0,0],"Q96377174":[5,0,0],"Q96391254":[5,0,0],"Q96603710":[8,0,0],"Q97930369":[5,0,0],"Q97930726":[5,0,0],"Q98893724":[5,0,0],"Q100930299":[8,0,0],"Q106472398":[5,0,0],"Q106548367":[8,0,0],"Q107665151":[8,0,0],"Q108810308":[5,0,0],"Q109016246":[5,0,0],"Q109413037":[8,0,0],"Q111844749":[8,0,0],"Q113288909":[8,0,0],"Q113540736":[5,0,0],"Q113793937":[11,0,0],"Q115109288":[5,0,0],"Q115137359":[5,0,0],"Q115244932":[5,0,0],"Q115287465":[5,0,0],"Q115325093":[5,0,0],"Q115325121":[5,0,0],"Q115428248":[5,0,0],"Q115452165":[8,0,0],"Q115767427":[5,0,0],"Q115776460":[5,0,0],"Q115778105":[5,0,0],"Q115804311":[5,0,0],"Q115804442":[5,0,0],"Q115804850":[5,0,0],"Q115804942":[10,0,0],"Q115805460":[5,0,0],"Q115805561":[5,0,0],"Q115811406":[8,0,0],"Q115816544":[5,0,0],"Q115857684":[5,0,0],"Q116265550":[5,0,0],"Q116753634":[5,0,0],"Q116969227":[5,0,0],"Q117706379":[8,0,0],"Q117886626":[5,0,0],"Q118502875":[8,0,0],"Q120146328":[5,0,0],"Q120177389":[5,0,0],"Q120252967":[8,0,0],"Q122782003":[8,0,0],"Q124322369":[5,0,0],"Q124333359":[5,0,0],"Q124372291":[5,0,0],"Q125869204":[5,0,0],"Q130341191":[8,0,0],"Q130760918":[5,0,0],"Q130824447":[5,0,0],"Q133824874":[5,0,0],"Q134301071":[5,0,0],"Q134605558":[8,0,0],"Q134718795":[5,0,0],"Q136499342":[5,0,0],"Q136499593":[5,0,0],"Q136500675":[5,0,0],"Q136772665":[5,0,0],"Q137506886":[8,0,0],"Q137580001":[5,0,0],"Q137580145":[5,0,0],"Q137609287":[5,0,0],"Q137636614":[5,0,0],"Q137690626":[5,0,0],"Q137825983":[5,0,0],"Q138803408":[5,0,0],"Q140800708":[5,0,0],"Q141906113":[5,0,0],"Q141913185":[5,0,0]}}

=== JigSawFr/PlayInsights/platforms/3ds/popular.json
{"schema":1,"platform":"3ds","generated":"2026-10-30","month":"2026-09","views":true,"source":"Wikidata (P400, sitelinks), Wikimedia pageviews (en.wikipedia)","games":{"CTR-A49":[8,0,0],"CTR-A66":[15,0,0],"CTR-A8F":[5,0,0],"CTR-A9A":[22,0,0],"CTR-A9E":[8,0,0],"CTR-AA8":[20,0,0],"CTR-AAC":[15,0,0],"CTR-AAH":[16,0,0],"CTR-AAL":[8,0,0],"CTR-ABA":[5,0,0],"CTR-ABB":[18,0,0],"CTR-ABE":[25,0,0],"CTR-ABL":[8,0,0],"CTR-ABM":[22,0,0],"CTR-ABN":[19,0,0],"CTR-ABQ":[19,0,0],"CTR-ABR":[24,0,0],"CTR-ABS":[12,0,0],"CTR-ABW":[16,0,0],"CTR-AC7":[18,0,0],"CTR-AC8":[17,0,0],"CTR-AC9":[12,0,0],"CTR-ACA":[20,0,0],"CTR-ACC":[20,0,0],"CTR-ACF":[21,0,0],"CTR-ACL":[15,0,0],"CTR-ACM":[23,0,0],"CTR-ACN":[18,0,0],"CTR-ACP":[10,0,0],"CTR-ACQ":[10,0,0],"CTR-ACV":[5,0,0],"CTR-ACZ":[5,0,0],"CTR-AD2":[5,0,0],"CTR-AD4":[18,0,0],"CTR-ADD":[19,0,0],"CTR-ADE":[10,0,0],"CTR-ADH":[8,0,0],"CTR-ADL":[12,0,0],"CTR-ADM":[5,0,0],"CTR-ADQ":[21,0,0],"CTR-ADR":[19,0,0],"CTR-ADT":[8,0,0],"CTR-AEB":[12,0,0],"CTR-AEG":[5,0,0],"CTR-AF3":[5,0,0],"CTR-AF8":[58,-41,0],"CTR-AFD":[5,0,0],"CTR-AFE":[21,0,0],"CTR-AFJ":[16,0,0],"CTR-AFL":[18,0,0],"CTR-AFR":[13,0,0],"CTR-AG3":[8,0,0],"CTR-AG5":[23,0,0],"CTR-AG6":[20,0,0],"CTR-AGA":[21,0,0],"CTR-AGF":[15,0,0],"CTR-AGG":[24,0,0],"CTR-AGK":[21,0,0],"CTR-AGL":[15,0,0],"CTR-AGP":[12,0,0],"CTR-AGR":[17,0,0],"CTR-AGU":[8,0,0],"CTR-AH6":[13,0,0],"CTR-AH8":[5,0,0],"CTR-AHC":[13,0,0],"CTR-AHF":[5,0,0],"CTR-AHP":[22,0,0],"CTR-AHR":[15,0,0],"CTR-AHS":[5,0,0],"CTR-AHX":[13,0,0],"CTR-AHY":[12,0,0],"CTR-AJ3":[20,0,0],"CTR-AJ8":[19,0,0],"CTR-AJ9":[5,0,0],"CTR-AJB":[13,0,0],"CTR-AJC":[5,0,0],"CTR-AJH":[13,0,0],"CTR-AJJ":[20,0,0],"CTR-AJR":[20,0,0],"CTR-AK2":[10,0,0],"CTR-AK3":[13,0,0],"CTR-AK8":[12,0,0],"CTR-AKG":[20,0,0],"CTR-AKH":[24,0,0],"CTR-AKK":[20,0,0],"CTR-AKM":[12,0,0],"CTR-AKS":[24,0,0],"CTR-AL4":[12,0,0],"CTR-AL6":[20,0,0],"CTR-ALA":[20,0,0],"CTR-ALC":[19,0,0],"CTR-ALE":[22,0,0],"CTR-ALF":[12,0,0],"CTR-ALG":[21,0,0],"CTR-ALL":[22,0,0],"CTR-ALZ":[16,0,0],"CTR-AM4":[8,0,0],"CTR-AM7":[68,-11,0],"CTR-AMC":[15,0,0],"CTR-AMD":[13,0,0],"CTR-AMJ":[23,0,0],"CTR-AMK":[60,14,0],"CTR-AMQ":[16,0,0],"CTR-AMX":[21,0,0],"CTR-AN3":[8,0,0],"CTR-AN4":[8,0,0],"CTR-AND":[24,0,0],"CTR-ANR":[20,0,0],"CTR-ANS":[61,-22,0],"CTR-ANT":[15,0,0],"CTR-ANX":[15,0,0],"CTR-APD":[22,0,0],"CTR-APG":[15,0,0],"CTR-API":[8,0,0],"CTR-APO":[8,0,0],"CTR-APP":[15,0,0],"CTR-APR":[15,0,0],"CTR-AQ2":[19,0,0],"CTR-AQ7":[16,0,0],"CTR-AQ8":[12,0,0],"CTR-AQE":[21,0,0],"CTR-AQL":[12,0,0],"CTR-AQN":[15,0,0],"CTR-AQQ":[20,0,0],"CTR-AQR":[5,0,0],"CTR-AR2":[8,0,0],"CTR-AR4":[17,0,0],"CTR-AR5":[13,0,0],"CTR-ARE":[61,9,0],"CTR-ARF":[8,0,0],"CTR-ARM":[62,11,0],"CTR-ARR":[19,0,0],"CTR-ART":[18,0,0],"CTR-ARV":[23,0,0],"CTR-AS3":[65,-11,0],"CTR-AS4":[8,0,0],"CTR-AS7":[20,0,0],"CTR-AS8":[20,0,0],"CTR-AS9":[5,0,0],"CTR-ASD":[19,0,0],"CTR-ASF":[21,0,0],"CTR-ASG":[15,0,0],"CTR-ASH":[10,0,0],"CTR-ASL":[18,0,0],"CTR-ASM":[19,0,0],"CTR-ASP":[22,0,0],"CTR-ASR":[18,0,0],"CTR-ASS":[12,0,0],"CTR-ASV":[15,0,0],"CTR-ASX":[5,0,0],"CTR-ASZ":[5,0,0],"CTR-AT8":[12,0,0],"CTR-ATA":[21,0,0],"CTR-ATH":[19,0,0],"CTR-ATK":[19,0,0],"CTR-ATL":[13,0,0],"CTR-ATN":[20,0,0],"CTR-ATS":[23,0,0],"CTR-ATT":[15,0,0],"CTR-AUN":[19,0,0],"CTR-AVH":[15,0,0],"CTR-AVM":[13,0,0],"CTR-AWA":[21,0,0],"CTR-AWE":[21,0,0],"CTR-AWR":[8,0,0],"CTR-AWS":[5,0,0],"CTR-AWW":[5,0,0],"CTR-AXC":[8,0,0],"CTR-AXR":[23,0,0],"CTR-AXX":[20,0,0],"CTR-AY3":[10,0,0],"CTR-AY9":[17,0,0],"CTR-AYE":[16,0,0],"CTR-AYM":[22,0,0],"CTR-AYN":[20,0,0],"CTR-AYW":[18,0,0],"CTR-AYX":[5,0,0],"CTR-AZE":[18,0,0],"CTR-AZG":[10,0,0],"CTR-AZJ":[5,0,0],"CTR-AZO":[5,0,0],"CTR-BAA":[22,0,0],"CTR-BAG":[17,0,0],"CTR-BAL":[21,0,0],"CTR-BB3":[19,0,0],"CTR-BBP":[12,0,0],"CTR-BC4":[8,0,0],"CTR-BC5":[13,0,0],"CTR-BCA":[19,0,0],"CTR-BCE":[15,0,0],"CTR-BD7":[8,0,0],"CTR-BDL":[15,0,0],"CTR-BE4":[8,0,0],"CTR-BFD":[17,0,0],"CTR-BFG":[5,0,0],"CTR-BFN":[12,0,0],"CTR-BFT":[58,-50,0],"CTR-BFX":[5,0,0],"CTR-BFY":[5,0,0],"CTR-BG2":[15,0,0],"CTR-BG4":[18,0,0],"CTR-BG6":[21,0,0],"CTR-BG9":[8,0,0],"CTR-BGM":[12,0,0],"CTR-BGX":[22,0,0],"CTR-BHD":[15,0,0],"CTR-BHR":[21,0,0],"CTR-BKK":[8,0,0],"CTR-BLD":[13,0,0],"CTR-BLF":[20,0,0],"CTR-BLH":[20,0,0],"CTR-BLJ":[22,0,0],"CTR-BLL":[15,0,0],"CTR-BLM":[16,0,0],"CTR-BLN":[15,0,0],"CTR-BLS":[16,0,0],"CTR-BLW":[22,0,0],"CTR-BM9":[13,0,0],"CTR-BMU":[15,0,0],"CTR-BNU":[12,0,0],"CTR-BPC":[19,0,0],"CTR-BPE":[8,0,0],"CTR-BPJ":[19,0,0],"CTR-BPM":[12,0,0],"CTR-BPN":[13,0,0],"CTR-BPP":[13,0,0],"CTR-BPX":[21,0,0],"CTR-BR3":[5,0,0],"CTR-BRB":[5,0,0],"CTR-BRC":[17,0,0],"CTR-BRG":[12,0,0],"CTR-BRM":[8,0,0],"CTR-BRP":[8,0,0],"CTR-BS3":[15,0,0],"CTR-BS6":[19,0,0],"CTR-BS8":[5,0,0],"CTR-BS9":[19,0,0],"CTR-BSE":[20,0,0],"CTR-BSF":[20,0,0],"CTR-BSK":[15,0,0],"CTR-BSY":[18,0,0],"CTR-BTE":[70,-12,0],"CTR-BTH":[16,0,0],"CTR-BTK":[8,0,0],"CTR-BTM":[20,0,0],"CTR-BTR":[22,0,0],"CTR-BTS":[19,0,0],"CTR-BUW":[15,0,0],"CTR-BWD":[13,0,0],"CTR-BXL":[13,0,0],"CTR-BXX":[20,0,0],"CTR-BYG":[5,0,0],"CTR-BYH":[5,0,0],"CTR-BYS":[5,0,0],"CTR-BZH":[8,0,0],"CTR-BZL":[24,0,0],"CTR-BZM":[13,0,0],"CTR-BZP":[25,0,0],"CTR-EA3":[23,0,0],"CTR-EC6":[23,0,0],"CTR-ECD":[15,0,0],"CTR-EDH":[22,0,0],"CTR-JA2":[13,0,0],"CTR-JAM":[15,0,0],"CTR-JAR":[5,0,0],"CTR-JAU":[15,0,0],"CTR-JB7":[19,0,0],"CTR-JBB":[5,0,0],"CTR-JBC":[15,0,0],"CTR-JBK":[5,0,0],"CTR-JBL":[5,0,0],"CTR-JC6":[25,0,0],"CTR-JCA":[18,0,0],"CTR-JCJ":[8,0,0],"CTR-JCN":[5,0,0],"CTR-JCP":[15,0,0],"CTR-JCZ":[5,0,0],"CTR-JD8":[13,0,0],"CTR-JD9":[24,0,0],"CTR-JDM":[5,0,0],"CTR-JEL":[8,0,0],"CTR-JEU":[23,0,0],"CTR-JEV":[5,0,0],"CTR-JF4":[5,0,0],"CTR-JFD":[10,0,0],"CTR-JFE":[63,19,0],"CTR-JFK":[5,0,0],"CTR-JGC":[15,0,0],"CTR-JGW":[12,0,0],"CTR-JHN":[5,0,0],"CTR-JHS":[8,0,0],"CTR-JK8":[5,0,0],"CTR-JKE":[10,0,0],"CTR-JKF":[8,0,0],"CTR-JKV":[8,0,0],"CTR-JKZ":[15,0,0],"CTR-JL2":[5,0,0],"CTR-JMD":[15,0,0],"CTR-JMF":[10,0,0],"CTR-JMG":[10,0,0],"CTR-JMS":[5,0,0],"CTR-JNS":[8,0,0],"CTR-JNU":[8,0,0],"CTR-JPM":[8,0,0],"CTR-JRG":[10,0,0],"CTR-JRJ":[5,0,0],"CTR-JRS":[5,0,0],"CTR-JRZ":[8,0,0],"CTR-JS4":[5,0,0],"CTR-JSA":[18,0,0],"CTR-JST":[18,0,0],"CTR-JT4":[13,0,0],"CTR-JT6":[5,0,0],"CTR-JUC":[10,0,0],"CTR-JUE":[15,0,0],"CTR-JUY":[8,0,0],"CTR-JV7":[16,0,0],"CTR-JVA":[10,0,0],"CTR-JVQ":[10,0,0],"CTR-JVV":[25,0,0],"CTR-JWC":[5,0,0],"CTR-JWG":[10,0,0],"CTR-JWP":[8,0,0],"CTR-JWV":[16,0,0],"CTR-JWX":[5,0,0],"CTR-JY5":[15,0,0],"CTR-JYL":[18,0,0],"CTR-JZG":[5,0,0],"CTR-KAA":[12,0,0],"CTR-KAS":[5,0,0],"CTR-KAW":[5,0,0],"CTR-KBW":[5,0,0],"CTR-KCA":[13,0,0],"CTR-KCC":[5,0,0],"CTR-KCD":[15,0,0],"CTR-KCK":[13,0,0],"CTR-KCN":[5,0,0],"CTR-KEP":[5,0,0],"CTR-KFL":[10,0,0],"CTR-KGB":[13,0,0],"CTR-KGW":[8,0,0],"CTR-KJE":[5,0,0],"CTR-KMG":[10,0,0],"CTR-KMJ":[5,0,0],"CTR-KMV":[13,0,0],"CTR-KMZ":[8,0,0],"CTR-KND":[5,0,0],"CTR-KPR":[5,0,0],"CTR-KQD":[13,0,0],"CTR-KQS":[5,0,0],"CTR-KR9":[8,0,0],"CTR-KRH":[5,0,0],"CTR-KSV":[16,0,0],"CTR-KSZ":[5,0,0],"CTR-KT6":[5,0,0],"CTR-KTW":[12,0,0],"CTR-KW4":[15,0,0],"CTR-KZS":[8,0,0],"CTR-KZV":[15,0,0],"CTR-NAC":[5,0,0],"KTR-CAF":[5,0,0],"KTR-CDP":[5,0,0],"KTR-CF3":[5,0,0]}}
