=== JigSawFr/PlayInsights/schemas/platforms/3ds/games.schema.json
{
 "$schema": "https://json-schema.org/draft/2020-12/schema",
 "title": "A platform's games: name, Wikidata item, release, reviews, traits",
 "type": "object",
 "required": [
  "schema",
  "generated",
  "games"
 ],
 "properties": {
  "schema": {
   "const": 1
  },
  "generated": {
   "type": "string",
   "pattern": "^\\d{4}-\\d{2}-\\d{2}$"
  },
  "source": {
   "type": "string"
  },
  "platform": {
   "type": "string"
  },
  "license": {
   "type": "string"
  },
  "part": {
   "type": "integer"
  },
  "parts": {
   "type": "integer"
  },
  "tags": {
   "type": "object",
   "additionalProperties": {
    "type": "string"
   }
  },
  "games": {
   "type": "object",
   "additionalProperties": {
    "type": "object",
    "properties": {
     "name": {
      "type": "string"
     },
     "qid": {
      "type": "string",
      "pattern": "^Q\\d+$"
     },
     "release": {
      "type": "integer",
      "minimum": 0,
      "maximum": 99991231
     },
     "slug": {
      "type": "string"
     },
     "pack": {
      "type": "boolean"
     },
     "coming_soon": {
      "type": "boolean"
     },
     "reviews": {
      "type": "array",
      "items": {
       "type": "integer"
      },
      "minItems": 2,
      "maxItems": 2
     },
     "rating": {
      "type": "array",
      "items": {
       "type": "integer"
      },
      "minItems": 2,
      "maxItems": 2
     },
     "igdb_rating": {
      "type": "array",
      "items": {
       "type": "number"
      },
      "minItems": 2,
      "maxItems": 2
     },
     "gamepass": {
      "type": "array",
      "items": {
       "enum": [
        "console",
        "pc"
       ]
      }
     },
     "ps": {
      "type": "array",
      "items": {
       "type": "string",
       "pattern": "^[0-9]+$"
      }
     },
     "ps_product": {
      "type": "array",
      "items": {
       "type": "string"
      }
     },
     "platforms": {
      "type": "array",
      "items": {
       "type": "array",
       "prefixItems": [
        {
         "type": "string"
        },
        {
         "type": "string"
        }
       ],
       "minItems": 2,
       "maxItems": 2
      }
     },
     "series": {
      "type": "array",
      "items": {
       "anyOf": [
        {
         "type": "array",
         "prefixItems": [
          {
           "type": "string"
          },
          {
           "type": "string"
          }
         ],
         "minItems": 2,
         "maxItems": 2
        },
        {
         "type": "integer"
        }
       ]
      }
     },
     "developers": {
      "type": "array",
      "items": {
       "anyOf": [
        {
         "type": "array",
         "prefixItems": [
          {
           "type": "string"
          },
          {
           "type": "string"
          }
         ],
         "minItems": 2,
         "maxItems": 2
        },
        {
         "type": "integer"
        }
       ]
      }
     },
     "publishers": {
      "type": "array",
      "items": {
       "anyOf": [
        {
         "type": "array",
         "prefixItems": [
          {
           "type": "string"
          },
          {
           "type": "string"
          }
         ],
         "minItems": 2,
         "maxItems": 2
        },
        {
         "type": "integer"
        }
       ]
      }
     },
     "genres": {
      "type": "array",
      "items": {
       "anyOf": [
        {
         "type": "array",
         "prefixItems": [
          {
           "type": "string"
          },
          {
           "type": "string"
          }
         ],
         "minItems": 2,
         "maxItems": 2
        },
        {
         "type": "integer"
        }
       ]
      }
     },
     "modes": {
      "type": "array",
      "items": {
       "anyOf": [
        {
         "type": "array",
         "prefixItems": [
          {
           "type": "string"
          },
          {
           "type": "string"
          }
         ],
         "minItems": 2,
         "maxItems": 2
        },
        {
         "type": "integer"
        }
       ]
      }
     },
     "tags": {
      "type": "array",
      "items": {
       "anyOf": [
        {
         "type": "array",
         "prefixItems": [
          {
           "type": "string"
          },
          {
           "type": "string"
          }
         ],
         "minItems": 2,
         "maxItems": 2
        },
        {
         "type": "integer"
        }
       ]
      }
     },
     "themes": {
      "type": "array",
      "items": {
       "anyOf": [
        {
         "type": "array",
         "prefixItems": [
          {
           "type": "string"
          },
          {
           "type": "string"
          }
         ],
         "minItems": 2,
         "maxItems": 2
        },
        {
         "type": "integer"
        }
       ]
      }
     },
     "keywords": {
      "type": "array",
      "items": {
       "anyOf": [
        {
         "type": "array",
         "prefixItems": [
          {
           "type": "string"
          },
          {
           "type": "string"
          }
         ],
         "minItems": 2,
         "maxItems": 2
        },
        {
         "type": "integer"
        }
       ]
      }
     },
     "perspectives": {
      "type": "array",
      "items": {
       "anyOf": [
        {
         "type": "array",
         "prefixItems": [
          {
           "type": "string"
          },
          {
           "type": "string"
          }
         ],
         "minItems": 2,
         "maxItems": 2
        },
        {
         "type": "integer"
        }
       ]
      }
     },
     "steam": {
      "type": "object",
      "required": [
       "app"
      ],
      "properties": {
       "app": {
        "type": "integer"
       },
       "positive": {
        "type": "integer",
        "minimum": 0
       },
       "negative": {
        "type": "integer",
        "minimum": 0
       },
       "owners": {
        "type": "integer",
        "minimum": 0
       },
       "ccu": {
        "type": "integer",
        "minimum": 0
       }
      }
     }
    }
   }
  }
 },
 "$id": "https://cdn.jsdelivr.net/gh/JigSawFr/Atlas@data/schemas/platforms/3ds/games.schema.json"
}

=== JigSawFr/PlayInsights/platforms/turbografx16/games.json
{"schema":1,"platform":"turbografx16","generated":"2026-10-30","source":"Wikidata (P400, P179, P178, P123, P136)","games":{"Q55535":{"name":"1943: The Battle of Midway","platforms":[["Q10683","PlayStation 3"],["Q99775","Commodore 64"],["Q100047","Commodore Amiga"],["Q23882","ZX Spectrum"],["Q172742","Nintendo Entertainment System"],["Q627302","Atari ST"],["Q192851",""],["Q1057377",""],["Q478829",""]],"series":[["Q108370485","19XX"]],"developers":[["Q14428","Capcom"]],"publishers":[["Q14428","Capcom"],["Q1930918","U.S. Gold"]],"genres":[["Q1044478","shoot 'em up"]]},"Q55607":{"name":"Bonanza Bros.","platforms":[["Q8079","Wii"],["Q99775","Commodore 64"],["Q100047","Commodore Amiga"],["Q23882","ZX Spectrum"],["Q10676","Sega Genesis/Mega Drive"],["Q209868","Sega Master System"],["Q1057377",""],["Q478829",""]],"developers":[["Q122741","Sega"],["Q1930918","U.S. Gold"]],"publishers":[["Q122741","Sega"]],"genres":[["Q270948","action game"],["Q828322","platform game"],["Q858523","stealth game"],["Q1223895","side-scrolling video game"]]},"Q55673":{"name":"R-Type","platforms":[["Q100047","Commodore Amiga"],["Q99775","Commodore 64"],["Q23882","ZX Spectrum"],["Q627302","Atari ST"],["Q853547","MSX"],["Q209868","Sega Master System"],["Q192851",""],["Q1057377",""],["Q478829",""]],"series":[["Q3414918","R-Type"]],"developers":[["Q383538","Compile"],["Q617752","Irem"]],"publishers":[["Q617752","Irem"]],"genres":[["Q1044478","shoot 'em up"],["Q27670585","science fiction video game"]]},"Q90994":{"name":"Chase H.Q.","platforms":[["Q8079","Wii"],["Q99775","Commodore 64"],["Q23882","ZX Spectrum"],["Q100047","Commodore Amiga"],["Q183259","Super Nintendo Entertainment System"],["Q172742","Nintendo Entertainment System"],["Q627302","Atari ST"],["Q853547","MSX"],["Q186437","Game Boy"],["Q1057377",""],["Q478829",""]],"series":[["Q112189113","Chase H.Q."]],"developers":[["Q1054844","Taito"]],"publishers":[["Q1054844","Taito"]],"genres":[["Q860750","racing video game"]]},"Q191965":{"name":"Zero Wing","platforms":[["Q10676","Sega Genesis/Mega Drive"],["Q192851",""],["Q1057377",""]],"developers":[["Q2291232","Toaplan"]],"publishers":[["Q122741","Sega"],["Q1054844","Taito"],["Q2291232","Toaplan"],["Q4042038","Kaga Create"]],"genres":[["Q1044478","shoot 'em up"],["Q96146141","horizontally scrolling shooter"]]},"Q265666":{"name":"Jim Power in Mutant Planet","platforms":[["Q100047","Commodore Amiga"],["Q10676","Sega Genesis/Mega Drive"],["Q183259","Super Nintendo Entertainment System"],["Q1057377",""],["Q478829",""]],"publishers":[["Q3259558","Loriciels"]],"genres":[["Q828322","platform game"]]},"Q288958":{"name":"Operation Wolf","platforms":[["Q99775","Commodore 64"],["Q23882","ZX Spectrum"],["Q100047","Commodore Amiga"],["Q209868","Sega Master System"],["Q172742","Nintendo Entertainment System"],["Q627302","Atari ST"],["Q853547","MSX"],["Q1057377",""],["Q478829",""]],"developers":[["Q1054844","Taito"]],"publishers":[["Q1054844","Taito"]],"genres":[["Q1044478","shoot 'em up"],["Q3965952","light-gun shooter"],["Q15613992","arcade"]]},"Q374820":{"name":"Darius","platforms":[["Q100047","Commodore Amiga"],["Q23882","ZX Spectrum"],["Q627302","Atari ST"],["Q186437","Game Boy"],["Q188642","Game Boy Advance"],["Q1057377",""]],"series":[["Q4037027","Darius"]],"developers":[["Q1054844","Taito"]],"publishers":[["Q1054844","Taito"]],"genres":[["Q1044478","shoot 'em up"]]},"Q388247":{"name":"Might and Magic III: Isles of Terra","platforms":[["Q100047","Commodore Amiga"],["Q10676","Sega Genesis/Mega Drive"],["Q183259","Super Nintendo Entertainment System"],["Q1047516","Sega CD/Mega CD"],["Q1057377",""]],"series":[["Q902176","Might and Magic"]],"developers":[["Q1889419","New World Computing"]],"publishers":[["Q1889419","New World Computing"]],"genres":[["Q744038","role-playing video game"]]},"Q388566":{"name":"Blazing Lazers","platforms":[["Q56942","Wii U"],["Q170325","PlayStation Portable"],["Q1057377",""]],"developers":[["Q1049502","Hudson Soft"]],"publishers":[["Q219203","NEC"]],"genres":[["Q1044478","shoot 'em up"]]},"Q588526":{"name":"Splatterhouse","platforms":[["Q192851",""],["Q1057377",""]],"series":[["Q4049946","Splatterhouse"]],"developers":[["Q309996","Namco"]],"publishers":[["Q309996","Namco"]],"genres":[["Q401831","beat 'em up"]]},"Q627021":{"name":"Wonder Boy III: The Dragon's Trap","platforms":[["Q209868","Sega Master System"],["Q1057377",""]],"developers":[["Q7989503","Westone Bit Entertainment"]],"publishers":[["Q122741","Sega"],["Q1049502","Hudson Soft"]],"genres":[["Q828322","platform game"],["Q19643088","Metroidvania"]]},"Q636411":{"name":"Might and Magic Book One: The Secret of the Inner Sanctum","platforms":[["Q99775","Commodore 64"],["Q172742","Nintendo Entertainment System"],["Q853547","MSX"],["Q1057377",""]],"series":[["Q902176","Might and Magic"]],"developers":[["Q1889419","New World Computing"]],"publishers":[["Q2664679","Gakken Holdings"]],"genres":[["Q744038","role-playing video game"]]},"Q643964":{"name":"Sherlock Holmes: Consulting Detective","platforms":[["Q1047516","Sega CD/Mega CD"],["Q1057377",""]],"developers":[["Q979198","ICOM Simulations"]],"publishers":[["Q979198","ICOM Simulations"]],"genres":[["Q23916","adventure video game"]]},"Q650804":{"name":"Dungeon Explorer","platforms":[["Q10676","Sega Genesis/Mega Drive"],["Q170325","PlayStation Portable"],["Q1057377",""]],"developers":[["Q780528","Atlus"]],"publishers":[["Q1049502","Hudson Soft"]],"genres":[["Q744038","role-playing video game"],["Q1163960","hack and slash"],["Q1422746","action role-playing game"]]},"Q672380":{"name":"Loom","platforms":[["Q100047","Commodore Amiga"],["Q627302","Atari ST"],["Q1057377",""]],"developers":[["Q216611","Lucasfilm Games"]],"publishers":[["Q186394","Fujitsu"],["Q216611","Lucasfilm Games"]],"genres":[["Q23916","adventure video game"]]},"Q677764":{"name":"Klax","platforms":[["Q100047","Commodore Amiga"],["Q99775","Commodore 64"],["Q23882","ZX Spectrum"],["Q10676","Sega Genesis/Mega Drive"],["Q172742","Nintendo Entertainment System"],["Q209868","Sega Master System"],["Q751719","Game Gear"],["Q206261","Atari 2600"],["Q627302","Atari ST"],["Q853547","MSX"],["Q203992",""],["Q1057377",""],["Q478829",""]],"developers":[["Q1061580","Atari Games"]],"publishers":[["Q1061580","Atari Games"]],"genres":[["Q54767","puzzle video game"]]},"Q720701":{"name":"New Adventure Island","platforms":[["Q56942","Wii U"],["Q1057377",""]],"developers":[["Q7065431","Now Production"]],"publishers":[["Q1049502","Hudson Soft"]],"genres":[["Q828322","platform game"]]},"Q844223":{"name":"Romance of the Three Kingdoms III: Dragon of Destiny","platforms":[["Q10677","PlayStation"],["Q10676","Sega Genesis/Mega Drive"],["Q183259","Super Nintendo Entertainment System"],["Q1047516","Sega CD/Mega CD"],["Q1057377",""]],"series":[["Q904990","Romance of the Three Kingdoms"]],"developers":[["Q845047","Koei"]],"publishers":[["Q845047","Koei"]],"genres":[["Q2176159","turn-based strategy video game"]]},"Q851032":{"name":"Gain Ground","platforms":[["Q10676","Sega Genesis/Mega Drive"],["Q209868","Sega Master System"],["Q1057377",""]],"developers":[["Q122741","Sega"]],"publishers":[["Q122741","Sega"]],"genres":[["Q270948","action game"],["Q472055","strategy video game"],["Q1260861","tactical shooter"],["Q2313710","real-time tactics"]]},"Q864177":{"name":"Lemmings","platforms":[["Q99775","Commodore 64"],["Q100047","Commodore Amiga"],["Q23882","ZX Spectrum"],["Q10676","Sega Genesis/Mega Drive"],["Q172742","Nintendo Entertainment System"],["Q183259","Super Nintendo Entertainment System"],["Q209868","Sega Master System"],["Q229429","3DO"],["Q627302","Atari ST"],["Q1023103","CD-i"],["Q751719","Game Gear"],["Q478829",""],["Q1057377",""]],"series":[["Q18276721","Lemmings"]],"developers":[["Q94893","Rockstar North"]],"publishers":[["Q1933462","SCE Studio Liverpool"]],"genres":[["Q54767","puzzle video game"]]},"Q864340":{"name":"Wonder Boy in Monster Land","platforms":[["Q100047","Commodore Amiga"],["Q99775","Commodore 64"],["Q23882","ZX Spectrum"],["Q209868","Sega Master System"],["Q627302","Atari ST"],["Q478829",""],["Q1057377",""]],"developers":[["Q122741","Sega"],["Q7989503","Westone Bit Entertainment"]],"publishers":[["Q200491","Activision"]],"genres":[["Q828322","platform game"]]},"Q906679":{"name":"Puyo Puyo 2","platforms":[["Q10680","PlayStation 2"],["Q10676","Sega Genesis/Mega Drive"],["Q10677","PlayStation"],["Q183259","Super Nintendo Entertainment System"],["Q192851",""],["Q1057377",""]],"series":[["Q1371583","Puyo Puyo"]],"developers":[["Q383538","Compile"]],"genres":[["Q54767","puzzle video game"]]},"Q907618":{"name":"Ys III: Wanderers from Ys","platforms":[["Q10676","Sega Genesis/Mega Drive"],["Q172742","Nintendo Entertainment System"],["Q183259","Super Nintendo Entertainment System"],["Q853547","MSX"],["Q1057377",""]],"series":[["Q8059691","Ys"]],"developers":[["Q1142226","Nihon Falcom"]],"publishers":[["Q840550","Alfa System"],["Q1142226","Nihon Falcom"]],"genres":[["Q1422746","action role-playing game"]]},"Q911802":{"name":"Parodius! From Myth to Laughter","platforms":[["Q172742","Nintendo Entertainment System"],["Q183259","Super Nintendo Entertainment System"],["Q192851",""],["Q1057377",""]],"series":[["Q7463585","Parodius"]],"developers":[["Q45700","Konami"]],"publishers":[["Q45700","Konami"]],"genres":[["Q1044478","shoot 'em up"]]},"Q963231":{"name":"Nobunaga's Ambition: Bushou Fuunroku","platforms":[["Q10676","Sega Genesis/Mega Drive"],["Q10677","PlayStation"],["Q1057377",""]],"developers":[["Q845047","Koei"]],"publishers":[["Q845047","Koei"]],"genres":[["Q3139142","grand strategy wargame"]]},"Q986330":{"name":"Valis II","platforms":[["Q10676","Sega Genesis/Mega Drive"],["Q853547","MSX"],["Q1057377",""]],"series":[["Q2663912","Valis"]],"developers":[["Q3177903","Telenet Japan"]],"publishers":[["Q3177903","Telenet Japan"]],"genres":[["Q23916","adventure video game"],["Q270948","action game"],["Q343568","action-adventure game"]]},"Q1046574":{"name":"Golden Axe","platforms":[["
